# Site settings
title: Stephen Schaub
email: sschaub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A technology blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sschaub.github.io" # the base hostname & protocol for your site
github_username:  sschaub

# Build settings
markdown: kramdown

# pdz8 settings
exclude: [
  sandbox/,
  website.*,
  ]
permalink: /posts/:title
enable_disqus: false
enable_social: false
